# Sigrid configuration file to enable security analysis
# This file configures Sigrid to analyze security vulnerabilities

# Enable security analysis
security:
  enabled: true

# Language-specific security rules
analysis:
  javascript:
    security_rules:
      - sql_injection
      - xss
      - path_traversal
      - code_injection
      - unsafe_deserialization

  typescript:
    security_rules:
      - sql_injection
      - xss
      - path_traversal
      - code_injection
      - unsafe_deserialization

# Exclude patterns (if needed)
exclude:
  - "node_modules/**"
  - "*.test.ts"
  - "*.spec.ts"

# Include patterns for analysis
include:
  - "app/**/*.ts"
  - "app/**/*.js"
  - "components/**/*.ts"
  - "components/**/*.js"
  - "services/**/*.ts"
  - "utils/**/*.ts"
