# Build pipeline for Next.js application
# This pipeline handles dependency installation, linting, and building the application
# Converted from GitHub Actions workflow: .github/workflows/build.yml

trigger: none

pr:
  branches:
    include:
      - main
      - dev

# Enable manual trigger
schedules: []

pool:
  vmImage: "ubuntu-latest"

strategy:
  matrix:
    node_20:
      node_version: "20.x"
    node_22:
      node_version: "22.x"

steps:
  - checkout: self
    displayName: "Checkout code"

  - task: NodeTool@0
    displayName: "Setup Node.js $(node_version)"
    inputs:
      versionSpec: $(node_version)

  - task: Cache@2
    displayName: "Cache npm dependencies"
    inputs:
      key: 'npm | "$(Agent.OS)" | $(Build.SourcesDirectory)/package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(Pipeline.Workspace)/.npm

  - script: |
      npm config set cache $(Pipeline.Workspace)/.npm --global
      npm ci
    displayName: "Install dependencies"

  - script: npm run lint
    displayName: "Run linter"
    continueOnError: true

  - script: npm run build
    displayName: "Build application"

  - task: PublishBuildArtifacts@1
    displayName: "Upload build artifacts"
    condition: eq(variables['node_version'], '22.x')
    inputs:
      PathtoPublish: "$(Build.SourcesDirectory)/.next"
      ArtifactName: "build-output"
      publishLocation: "Container"
      retentionDays: 7

  - task: PublishBuildArtifacts@1
    displayName: "Upload package.json"
    condition: eq(variables['node_version'], '22.x')
    inputs:
      PathtoPublish: "$(Build.SourcesDirectory)/package.json"
      ArtifactName: "build-output"
      publishLocation: "Container"
