stages:
  - stage: Report
    jobs:
      - job: SigridCI
        pool:
          vmImage: ubuntu-latest
        container: softwareimprovementgroup/sigridci:azure
        continueOnError: true
        condition: "ne(variables['Build.SourceBranch'], 'refs/heads/dev')"
        steps:
          - bash: "sigridci.py --customer basicfit --system migration-playground --source ."
            env:
              SIGRID_CI_TOKEN: $(SIGRID_CI_TOKEN)
            continueOnError: true
      - job: SigridPublish
        pool:
          vmImage: ubuntu-latest
        container: softwareimprovementgroup/sigridci:azure
        continueOnError: true
        condition: "eq(variables['Build.SourceBranch'], 'refs/heads/dev')"
        steps:
          - bash: "sigridci.py --customer basicfit --system migration-playground --source . --publishonly"
            env:
              SIGRID_CI_TOKEN: $(SIGRID_CI_TOKEN)
            continueOnError: true
