pr:
  branches:
    include:
      - dev

trigger: none

stages:
  - stage: SigridAnalysis
    displayName: "Sigrid Code Quality Analysis"
    jobs:
      - job: SigridReportAndPublish
        displayName: "Generate Report and Publish"
        pool:
          vmImage: ubuntu-latest
        container: softwareimprovementgroup/sigridci:azure
        continueOnError: true
        steps:
          - bash: |
              echo "Running Sigrid analysis on PR to dev branch..."
              echo "Source branch: $(Build.SourceBranchName)"
              echo "Target branch: $(System.PullRequest.TargetBranch)"

              sigridci.py --customer basicfit --system migration-playground --source . --publish
            displayName: "Run Sigrid CI Analysis and Publish"
            env:
              SIGRID_CI_TOKEN: $(SIGRID_CI_TOKEN)
            continueOnError: true

          - bash: |
              echo "Sigrid analysis completed!"
              echo "Check the Sigrid dashboard for detailed results."
            displayName: "Analysis Summary"
            condition: always()
