# Trigger on PR to dev branch
pr:
  branches:
    include:
      - dev

# Disable CI trigger
trigger: none

stages:
  - stage: SigridAnalysis
    displayName: "Sigrid Code Quality Analysis"
    jobs:
      - job: SigridReportAndPublish
        displayName: "Generate Report and Publish"
        pool:
          vmImage: ubuntu-latest
        container: softwareimprovementgroup/sigridci:azure
        continueOnError: true
        steps:
          - bash: |
              echo "Running Sigrid analysis with security configuration..."
              echo "Source branch: $(Build.SourceBranchName)"
              echo "Target branch: $(System.PullRequest.TargetBranch)"

              # Check if configuration file exists
              if [ -f ".sigrid.yml" ]; then
                echo "Found Sigrid configuration file (.sigrid.yml)"
                cat .sigrid.yml
              else
                echo "No Sigrid configuration file found"
              fi

              # Run Sigrid with security analysis enabled
              sigridci.py \
                --customer basicfit \
                --system migration-playground \
                --source . \
                --publish \
                --include-security \
                --config .sigrid.yml
            displayName: "Run Sigrid CI Analysis with Security Config"
            env:
              SIGRID_CI_TOKEN: $(SIGRID_CI_TOKEN)
            continueOnError: true

          - bash: |
              echo "Sigrid analysis completed!"
              echo "Check the Sigrid dashboard for detailed results."
              echo ""
              echo "Security Analysis Summary:"
              echo "=========================="
              echo "- SQL Injection checks: Enabled"
              echo "- Code Injection checks: Enabled" 
              echo "- Path Traversal checks: Enabled"
              echo "- XSS checks: Enabled"
              echo "- Unsafe Deserialization checks: Enabled"
              echo ""
              echo "View full security report at: https://sigrid-says.com/basicfit/migration-playground"
            displayName: "Security Analysis Summary"
            condition: always()

          - bash: |
              # Optional: Parse Sigrid results for security findings
              echo "Checking for security vulnerabilities in results..."

              # This would typically parse Sigrid output files
              # Adjust based on actual Sigrid output format
              if [ -f "sigrid-ci-output.json" ]; then
                echo "Found Sigrid output file"
                # Parse for security findings
                grep -i "security\|vulnerability\|injection\|xss" sigrid-ci-output.json || echo "No security keywords found in output"
              else
                echo "No Sigrid output file found for detailed parsing"
              fi
            displayName: "Parse Security Results"
            condition: always()
            continueOnError: true
