# Test pipeline for Next.js application
# This pipeline runs unit tests, integration tests, and generates coverage reports
# Converted from GitHub Actions workflow: .github/workflows/test.yml

trigger:
  branches:
    include:
    - main
    - dev

pr:
  branches:
    include:
    - main
    - dev

# Enable manual trigger
schedules: []

pool:
  vmImage: 'ubuntu-latest'

variables:
  node_version: '22.x'

steps:
- checkout: self
  displayName: 'Checkout code'

- task: NodeTool@0
  displayName: 'Setup Node.js $(node_version)'
  inputs:
    versionSpec: $(node_version)

- task: Cache@2
  displayName: 'Cache npm dependencies'
  inputs:
    key: 'npm | "$(Agent.OS)" | package-lock.json'
    restoreKeys: |
      npm | "$(Agent.OS)"
    path: $(npm_config_cache)

- script: npm ci
  displayName: 'Install dependencies'

- script: npm test
  displayName: 'Run tests'

- script: npm run test:coverage
  displayName: 'Run tests with coverage'

- task: PublishBuildArtifacts@1
  displayName: 'Upload coverage reports'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/coverage'
    ArtifactName: 'coverage-report'
    publishLocation: 'Container'
    retentionDays: 30

- task: PublishCodeCoverageResults@2
  displayName: 'Publish code coverage results'
  inputs:
    summaryFileLocation: '$(Build.SourcesDirectory)/coverage/cobertura-coverage.xml'
    pathToSources: '$(Build.SourcesDirectory)'
    failIfCoverageEmpty: false

- script: |
    echo "## Test Coverage Summary"
    echo ""
    if [ -f coverage/coverage-summary.json ]; then
      cat coverage/coverage-summary.json
    else
      echo "Coverage summary not available"
    fi
  displayName: 'Display coverage summary'
