import { render, screen } from '@testing-library/react'
import RootLayout, { metadata } from './layout'

describe('RootLayout', () => {
  it('renders children correctly', () => {
    render(
      <RootLayout>
        <div data-testid="test-child">Test Child</div>
      </RootLayout>
    )

    const child = screen.getByTestId('test-child')
    expect(child).toBeInTheDocument()
    expect(child).toHaveTextContent('Test Child')
  })

  it('has correct metadata', () => {
    expect(metadata.title).toBe('Create Next App')
    expect(metadata.description).toBe('Generated by create next app')
  })
})
