import { metadata } from "../../app/layout";

describe("RootLayout", () => {
  it("has correct metadata", () => {
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });
});
